"use client";
import {useCallback,useEffect,useRef,useState} from "react";
type Aim={x:number;y:number}; type Result="GOAL"|"SAVED"|"MISS"|null;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export default function Home(){
 const [aim,setAim]=useState<Aim>({x:50,y:45}),[power,setPower]=useState(0),[charging,setCharging]=useState(false),[shooting,setShooting]=useState(false),[result,setResult]=useState<Result>(null),[score,setScore]=useState({goals:0,shots:0}),[target,setTarget]=useState<Aim>(aim),[keeper,setKeeper]=useState<Aim>({x:50,y:60}); const p=useRef(0),dir=useRef(1);
 const move=useCallback((x:number,y:number)=>{if(!shooting)setAim(a=>({x:clamp(a.x+x,12,88),y:clamp(a.y+y,12,82)}))},[shooting]);
 const charge=useCallback(()=>{if(!shooting){setResult(null);setCharging(true)}},[shooting]);
 const shoot=useCallback(()=>{if(!charging||shooting)return;setCharging(false);setShooting(true);setTarget(aim);const k={x:clamp(aim.x+(Math.random()-.5)*70,12,88),y:clamp(aim.y+(Math.random()-.5)*56,15,78)};setKeeper(k);const d=Math.hypot(aim.x-k.x,aim.y-k.y),miss=p.current>99&&(aim.y<16||aim.x<15||aim.x>85),out:Result=miss?"MISS":d<(p.current<40?16:10)?"SAVED":"GOAL";setTimeout(()=>{setResult(out);setScore(s=>({goals:s.goals+(out==="GOAL"?1:0),shots:s.shots+1}))},620);setTimeout(()=>{setShooting(false);p.current=0;setPower(0)},1500)},[aim,charging,shooting]);
 useEffect(()=>{if(!charging)return;const t=setInterval(()=>{let n=p.current+dir.current*2.2;if(n>=100){n=100;dir.current=-1}if(n<=0){n=0;dir.current=1}p.current=n;setPower(n)},20);return()=>clearInterval(t)},[charging]);
 useEffect(()=>{const kd=(e:KeyboardEvent)=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","Space"].includes(e.code))e.preventDefault();if(e.code==="ArrowLeft")move(-4,0);if(e.code==="ArrowRight")move(4,0);if(e.code==="ArrowUp")move(0,-4);if(e.code==="ArrowDown")move(0,4);if(e.code==="Space"&&!e.repeat)charge()},ku=(e:KeyboardEvent)=>{if(e.code==="Space")shoot()};addEventListener("keydown",kd);addEventListener("keyup",ku);return()=>{removeEventListener("keydown",kd);removeEventListener("keyup",ku)}},[move,charge,shoot]);
 return <main className="game"><header><div className="brand"><i>M</i><span><b>MESSI</b><small>PENALTY ARENA</small></span></div><div className="score">GOALS <b>{score.goals}</b><em/> SHOTS <b>{score.shots}</b></div><button onClick={()=>{setScore({goals:0,shots:0});setResult(null)}}>RESET MATCH</button></header>
 <section className="stadium"><div className="lights"/><div className="crowd"/><div className="goal"><div className="net"/><div className="posts"/><div className="aim" style={{left:`${aim.x}%`,top:`${aim.y}%`}}/><div className={`keeper ${shooting?"dive":""}`} style={shooting?{left:`${keeper.x}%`,top:`${keeper.y}%`}:undefined}><i/><b>1</b><span/></div><div className={`ball ${shooting?"fly":""}`} style={shooting?{"--x":`${target.x}%`,"--y":`${target.y}%`} as React.CSSProperties:undefined}>⬟</div>{result&&<div className={`result ${result.toLowerCase()}`}>{result}<small>{result==="GOAL"?"TOP CLASS FINISH":result==="SAVED"?"KEEPER READ IT":"JUST WIDE"}</small></div>}</div><div className="pitch"><i/></div><div className={`messi ${shooting?"kick":""}`}><div className="hair"/><div className="head"/><div className="shirt"><small>MESSI</small><b>10</b></div><i/><i/><span/><span/></div></section>
 <section className="hud"><div className="hint"><strong>01</strong><span><b>AIM YOUR SHOT</b><small>USE ARROW KEYS</small></span></div><div className="arrows"><button onClick={()=>move(0,-4)}>▲</button><button onClick={()=>move(-4,0)}>◀</button><button onClick={()=>move(0,4)}>▼</button><button onClick={()=>move(4,0)}>▶</button></div><div className="meter"><label><b>SHOT POWER</b><span>{Math.round(power)}%</span></label><div><i/><b style={{width:`${power}%`}}/></div><small>Release in the green zone for the cleanest strike</small></div><button className={`shoot ${charging?"active":""}`} onPointerDown={charge} onPointerUp={shoot} onPointerLeave={()=>charging&&shoot()}><b>{charging?"RELEASE!":"HOLD TO SHOOT"}</b><small>SPACEBAR</small></button></section></main>
}
